### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by MarcoOquendoC** [Aseadd/Capstone2#61]
# [JavaScript group capstone: set up your Kanban board](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md)

## Hello there,

- This is the [link](https://github.com/Aseadd/Capstone2/projects/1) to the project.
- There are 2 people in our group @Aseadd and @MarcoOquendoC.

![Patricio greeting](https://media.giphy.com/media/3ogwFGEHrVxusDbDjO/giphy.gif)

**Comment by phelian23** [comment]
Hi @MarcoOquendoC @Aseadd,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966](https://user-images.githubusercontent.com/85095702/187496067-b4d44aad-f28b-456c-af03-f525d7fced95.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
