### ISSUE TITLE
Peer to peer Code Review

### ISSUE THREAD

**Issue by cmolinan** [Aseadd/Capstone2#68]
![177408688-113768c1-53d0-4c38-9027-f3a87bd35cdb](https://user-images.githubusercontent.com/17918694/188171813-dd709e0f-dd85-4f31-96c7-ecc1c77b985b.gif)

Congratulations for your work. You have done a good job!
Here are some suggestions for improvement:

- Increase the number of items
- Make it responsive
It's almost finished now !!.

**Comment by MarcoOquendoC** [comment]
# Thanks Carlos, @cmolinan 

- We are considering your advices.
![Patrik May I take your hat sir](https://user-images.githubusercontent.com/104022866/182870404-d1748a2c-4f8f-42ba-a155-92a573134610.gif)
